spring:
  application:
    name: eureka-client-service
server:
  port: 9900
eureka:
  client:
    service-url:
      defaultZone: http://eurekaUser:$EurekaUser$@121.5.211.53:9999/eureka/
#      defaultZone: http://localhost:9999/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}
