spring:
  application:
    name: eureka-client-service
server:
  port: 9900
eureka:
  client:
    service-url:
      defaultZone: http://eurekaUser:$EurekaUser$@127.0.0.1:9999/eureka/
#      defaultZone: http://eurekaUser:EurekaUser2580@121.5.211.53:9999/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}
